### ISSUE TITLE
Assertion for URL: allow urls without http/https

### ISSUE THREAD

**Issue by AlexandreKilian** [ben-gibson/foursquare-venue-client#3]
Hello,

First of thanks for that Library, just what I needed :)
I discovered while testing that Foursquare isn't that strict on Venue URLs, allowing www.google.at for example. Thus, the Assertion fails when Foursquare returns a Venue with such a malformed URL. Since Foursquare isn't that strict, I'd propose following their rules and loosen that Assertion

**Comment by ben-gibson** [comment]
Thanks for this, I will take a look tomorrow. I haven't gotten around to using this library myself yet so let me know if you spot anything else that needs fixing or improving.

**Comment by ben-gibson** [comment]
Sorry, I haven't gotten around to looking at this yet. I aim to take a look this weekend!

**Comment by ben-gibson** [comment]
Fixed in #4 and released in version 0.0.2

**Comment by AlexandreKilian** [comment]
awesome, thx!
